### ISSUE TITLE
End to end auto scraping by zhihu round table topic

### ISSUE THREAD

**Issue by GeeYangML** [wangrui6/Zhihu-KOL#1]
Hi. 
I have created a script to auto scrape zhihu answers by round table topic. Can you add me to the contributor list so I make a PR ? You can view the script from my fork. https://github.com/MLMonkATGY/Zhihu-KOL

I noticed that your methods requires peoples id to start scraping. I have also created a util functions to get people id url from round table as Zhihu roundatable usually invites some KOL on that topic.

**Comment by GeeYangML** [comment]
I am using this headless browser.
https://playwright.dev/python/docs/intro
After installing the requirements.txt, you need to install the headless browser via command line.
`playwright install`

**Comment by GeeYangML** [comment]
[people.csv](https://github.com/wangrui6/Zhihu-KOL/files/10833396/people.csv)

**Comment by GeeYangML** [comment]
[zhihu.csv](https://github.com/wangrui6/Zhihu-KOL/files/10833397/zhihu.csv)

**Comment by wangrui6** [comment]
this is great!

**Comment by wangrui6** [comment]
Need to fix the Unicode issue in order to store and display Chinese
characters on my side. Now LGTM.
