### ISSUE TITLE
Timeout when crawling all href links in the question answer detail webpage

### ISSUE THREAD

**Issue by wangrui6** [wangrui6/Zhihu-KOL#11]
After the most recent change to Firefox and fix, we could find all available question answer detailed links in a topic url page. However, after re-running the code, the following line `all_hrefs = await get_all_href(page.locator(".QuestionAnswers-answers"))` in the function `end_to_end_auto_scrape_common_topics` gives rise to time out errors. This does not happen for the other function `end_to_end_auto_scrape` given it also has the same logic of scraping all hrefs in the same locator on the. page. The code is in the `issue-10` branch.

**Comment by GeeYangML** [comment]
The issue is mainly caused by different css selector between chrome and firefox.
